import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, mkdtempSync, copyFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { chromium } from 'playwright';
import { ProvenanceStore } from '../src/provenance.ts';
import { DatabaseSync } from 'node:sqlite';

const root = path.resolve(import.meta.dirname, '..');
const evidence = path.join(root, 'data', 'search-verification');
mkdirSync(evidence, { recursive: true });
const scratch = mkdtempSync(path.join(evidence, 'run-'));
const fixture = path.join(scratch, 'spotify.db');
copyFileSync(path.join(root, 'data', 'dev-fixture.db'), fixture);
const db = new DatabaseSync(fixture);
db.prepare('UPDATE liked_tracks SET removed_at = NULL WHERE track_id = ?').run('al01t1');
db.close();
const port = 18081;
const base = `http://127.0.0.1:${port}`;
const env = { ...process.env, PORT: String(port), SPOTIFY_DB: fixture };
for (const name of ['LIKES', 'PLAYLISTS', 'PROVENANCE', 'APP_PLAYS', 'UPGRADES', 'DISCOGS']) env[`${name}_DB`] = path.join(scratch, `${name}.db`);
env.JELLYFIN_URL = '';
const provenance = new ProvenanceStore(env.PROVENANCE_DB);
provenance.upsert([{ path: '/music/Offline Artist/Offline Album/Offline Song.flac', artist: 'Offline Artist', title: 'Offline Song', album: 'Offline Album', source: 'cd', codec: 'flac', duration_ms: 100000 }]);
provenance.close();
const server = spawn(process.execPath, ['src/server.ts'], { cwd: root, env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
let log = '';
server.stdout.on('data', b => { log += b; });
server.stderr.on('data', b => { log += b; });
let browser;
const checks = [];
async function json(url, init) { const response = await fetch(base + url, init); assert.equal(response.status, 200, await response.clone().text()); return response.json(); }
const post = (url, body) => json(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
try {
  for (let i = 0; i < 100; i++) {
    try { await json('/api/tracks'); break; } catch { if (i === 99) throw new Error(log); await new Promise(r => setTimeout(r, 100)); }
  }
  assert.deepEqual(await json('/api/search?q=a'), { songs: [], artists: [], albums: [], playlists: [] });
  assert.equal((await json('/api/search?q=%25%25')).songs.length, 0);
  const found = await json('/api/search?q=Local');
  assert(found.songs.length && found.artists.length && found.albums.length);
  const playlist = await post('/api/local-playlists', { name: 'Local verification playlist', trackIds: ['al01t1'] });
  assert((await json('/api/search?q=verification')).playlists.some(p => p.id === playlist.id));
  await post('/api/likes', { id: 'al01t1', liked: true });
  await post('/api/likes', { id: 'al01t1', liked: true });
  assert.equal((await json('/api/tracks')).filter(t => t.id === 'al01t1').length, 1);
  const snapshot = new DatabaseSync(fixture);
  snapshot.prepare('UPDATE liked_tracks SET removed_at = ? WHERE track_id = ?').run('2026-09-11', 'al01t1');
  snapshot.close();
  assert((await json('/api/tracks')).some(t => t.id === 'al01t1'));
  await post('/api/likes', { id: 'al01t1', liked: false });
  assert(!(await json('/api/tracks')).some(t => t.id === 'al01t1'));
  assert.equal((await fetch(base + '/api/likes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: 'missing', liked: true }) })).status, 404);
  const offline = await json('/api/search?q=Offline');
  assert.equal(offline.songs.length, 1);
  assert.equal(offline.artists[0].name, 'Offline Artist');
  assert.equal(offline.albums.length, 1);
  assert((await json('/api/album?id=' + encodeURIComponent(offline.albums[0].id))).album);
  assert.equal((await json('/api/artist?id=' + encodeURIComponent(offline.artists[0].id))).artist.name, 'Offline Artist');
  await post('/api/likes', { id: offline.songs[0].id, liked: true });
  assert((await json('/api/tracks')).some(t => t.id === offline.songs[0].id));
  checks.push('HTTP: short and literal queries, grouped search, local playlist, idempotent likes, Spotify removal, unlike, unknown track, local-only song/artist/album and like');
  browser = await chromium.launch();
  for (const width of [1440, 390, 320]) {
    const page = await browser.newPage({ viewport: { width, height: 900 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(base + '/liked');
    await page.getByRole('heading', { name: 'Liked songs', exact: true }).waitFor();
    const playerNode = await page.locator('#player-bar').elementHandle();
    assert.equal(await page.locator('#nav a[href="/albums"]').count(), 0);
    const input = page.getByRole('searchbox', { name: 'Search music' });
    await input.fill('Local');
    await page.getByRole('heading', { name: 'Artists', exact: true }).waitFor();
    await page.locator('#search-results [data-track-id="al01t1"]').waitFor();
    await page.locator('#search-results [data-track-id="al01t1"]').getByRole('button', { name: 'Add Streetlight Frequency to liked songs' }).click();
    await page.locator('#search-results [data-track-id="al01t1"]').getByRole('button', { name: 'Remove Streetlight Frequency from liked songs' }).waitFor();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(evidence, `search-${width}.png`), fullPage: true });
    await input.press('Escape');
    await page.getByRole('heading', { name: 'Liked songs', exact: true }).waitFor();
    assert(await input.evaluate(el => el === document.activeElement));
    assert(await playerNode.evaluate(el => el === document.querySelector('#player-bar')));
    await page.reload();
    await page.getByRole('button', { name: 'Remove Streetlight Frequency from liked songs' }).waitFor();
    await page.getByRole('button', { name: 'Remove Streetlight Frequency from liked songs' }).click();
    await page.locator('[data-track-id="al01t1"]').waitFor({ state: 'detached' });
    await input.fill('verification');
    await page.getByRole('link', { name: 'Local verification playlist' }).click();
    await page.getByRole('heading', { name: 'Local verification playlist' }).waitFor();
    assert.equal(await input.inputValue(), '');
    await input.fill('Offline');
    await page.getByRole('link', { name: 'Offline Artist', exact: true }).click();
    await page.getByRole('heading', { name: 'Offline Artist', exact: true }).waitFor();
    await page.route('**/api/likes', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Unavailable"}' }));
    await page.getByRole('button', { name: 'Remove Offline Song from liked songs' }).click();
    await page.getByRole('alert').filter({ hasText: 'Could not save like. Try again.' }).waitFor();
    await page.unroute('**/api/likes');
    await input.fill('zznothingzz');
    await page.getByText('No music found for "zznothingzz".').waitFor();
    await page.getByRole('button', { name: 'Close search' }).click();
    await page.route('**/api/search?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Unavailable"}' }));
    await input.fill('failure');
    await page.getByRole('button', { name: 'Retry', exact: true }).waitFor();
    await page.unroute('**/api/search?*');
    await page.getByRole('button', { name: 'Retry', exact: true }).click();
    await page.getByText('No music found for "failure".').waitFor();
    await input.fill('Local');
    await page.getByRole('heading', { name: 'Songs', exact: true }).waitFor();
    await input.fill('Mira');
    await page.getByRole('link', { name: 'Mira Vale', exact: true }).waitFor();
    assert.equal(await page.locator('#search-results').getByRole('link', { name: 'Local Signals', exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Close search' }).click();
    assert.deepEqual(errors, []);
    checks.push(`Browser ${width}px: search, grouped results, like, close, focus, reload, unlike, failed like, playlist and local artist navigation, empty/error/retry states, query replacement, player DOM preserved, no horizontal overflow or runtime errors`);
    await page.close();
  }
  writeFileSync(path.join(evidence, 'results.json'), JSON.stringify(checks, null, 2));
  console.log(checks.join('\n'));
} finally {
  await browser?.close();
  server.kill();
  await new Promise(resolve => { if (server.exitCode !== null) resolve(); else server.once('exit', resolve); });
  writeFileSync(path.join(evidence, 'server.log'), log);
  const restore = new DatabaseSync(fixture);
  restore.prepare('UPDATE liked_tracks SET removed_at = NULL WHERE track_id = ?').run('al01t1');
  restore.close();
}
